### ISSUE TITLE
predict from saved model

### ISSUE THREAD

**Issue by bachlaw** [skdeshpande91/flexBART#11]
Hi Sameer,

Are there any special requirements to predict from a fitted model besides saving the trees? Despite doing so, and confirming that the trees have been saved and the continuous predictors scaled to c(-1, 1), I get this error message consistently:

`Error in UseMethod("predict") : 
  no applicable method for 'predict' applied to an object of class "c('double', 'numeric')"`

The model is obviously a list so perhaps one of the model slots is not reporting what is expected? 

Thanks!

**Comment by skdeshpande91** [comment]
Are you using the function `predict_flexBART`? Or are you trying to use the generic `predict` function? I've not (yet) built support for the latter.

**Comment by bachlaw** [comment]
I did not know there could be a difference! And yes, I was using the generic not the more specific one. Thank you.

However, using the former I am now getting strange messages like `[get_bn]: could not find value of categorical predictor in either left or right cutset!` whether I use new test data or try to predict the original training data with the exact same vector specifications.  

With the main model function that usually indicates the categorical variables are listed in a different order somewhere in the model spec but it seems to be happening here even when I copy and paste the same predictor vectors into the predict specification for continuous and categorical.  I'll try to figure out why it is upset.

**Comment by skdeshpande91** [comment]
That error usually occurs when you've either (i) passed a value of the categorical predictor that's not supplied in the `cat_levels_list` object or (ii) not re-coded the categorical predictor to the integers {0, 1, ..., # categories - 1}.

**Comment by bachlaw** [comment]
That's what I thought so to I used the original training data to predict as a check to make sure I wasn't doing that and I am not.  There is one 0-coded categorical variable that is causing the issue (generating NaN values when present in the predicted data, but it is definitely in both sets. That makes me wonder if the issue could be combinations of categorical variables in different trees that it expects to see and does not? Perhaps that makes no sense, but the data works fine as "test" data in the original fit. I will keep thinking about it. Thanks for the replies!
