### ISSUE TITLE
a_cat, b_cat

### ISSUE THREAD

**Issue by bachlaw** [skdeshpande91/flexBART#14]
Hi Sameer,

What do these parameters control? Do they refer to a beta distribution governing either the sparsity prior or some specific prior to the categorical variables? Thanks!

**Comment by skdeshpande91** [comment]
They determine how the levels of an unstructured categorical variable are partitioned. By default, `flexBART` will assign levels to the left branch with probability 0.5. Currently, this is implemented by setting `a_cat = 0, b_cat = 0`. 
If you specify positive values for these parameters, levels are sent to the left with probability $\theta \sim \text{Beta}(a_{cat}, b_{cat}).$ That probability $\theta$ is drawn anew every time you propose splitting on a categorical level.


Anecdotally, I've not found using non-default values or tuning these particular parameters especially helpful, but your mileage may vary.
