### ISSUE TITLE
`flexBART()` for binary response?

### ISSUE THREAD

**Issue by AMBarbosa** [skdeshpande91/flexBART#7]
Hi,
The help file for `flexBART()` says `Y_train` should be a _Vector of continous responses for training data_ ("continuous" is slightly misspelled, by the way :). Any info on how it works for a binary response variable, or any plans to implement this? I'm not sure about the `BART` package, but I know the `dbarts::bart` function accommodates binary responses.
Cheers!

**Comment by skdeshpande91** [comment]
Thanks for pointing out the typo. For binary responses, use the function `probit_flexBART()`.

**Comment by AMBarbosa** [comment]
Thanks! Might be worth mentioning `probit_flexBART()` under a "See also" section in the `flexBART()` help file. Regards,
