### ISSUE TITLE
add `colnames` to the `varcounts` output matrix

### ISSUE THREAD

**Issue by AMBarbosa** [skdeshpande91/flexBART#8]
It would be great it the `varcounts` element of the object produced by `flexBART()` and by `probit_flexBART()` had `colnames` that allowed the user to analyze and plot the importance of each variable. Right now, it is unclear which of those columns correspond to the continuous and the categorical variables, and in any case the variable names should be able to be extracted (in the correct order) from the output object itself, without necessarily having access to the inputs. Cheers!

**Comment by skdeshpande91** [comment]
Thanks for the suggestion. The columns are ordered as follows: first the continuous predictors (in the order they are recorded in `X_cont_train`) and then the categorical predictors (in the order they are recorded in `X_cat_train`). In future versions, we will check for column names in the input and propagate them accordingly to the output.
